config/routes.rb
Rails.application.routes.draw do
    root    'chatroom#index'
    resources :users

    get     'login', to: 'sessions#new'
    post    'login', to: 'sessions#create'
    delete  'logout', to: 'sessions#destroy'
    post    'message', to: 'messages#create'

    mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    before_save { self.username = username.downcase }
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 12}
    validates :password, presence: true, length: {minimum: 6, maximum: 8}
    has_many :messages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    protect_from_forgery with: :exception

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user

    def index
        @messages = Message.custom_display
        @message = Message.new
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user

    def create
        message = current_user.messages.build(message_params)
        if message.save
            ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(message)
        end
    end

    private

    def message_params
        params.require(:message).permit(:body)
    end

    def message_render(message)
        render(partial: 'message', locals: {message: message})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :logged_in_redirect, only: [:new, :create]

    def new
    end

    def create
        user = User.find_by(username: params[:session][:username].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:positive] = "You have successfully signed in!"
            redirect_to user_path(user)
        else
            flash.now[:negative] = "Invalid username/password"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:positive] = "Successfully signed out"
        redirect_to login_path
    end

    private

    def logged_in_redirect
        if logged_in?
            flash[:negative] = "You are already logged in"
            redirect_to root_path
        end
    end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show, :destroy]

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          flash[:positive] = "Welcome to the chatroom #{@user.username}"
          redirect_to user_path(@user)
        else
          render 'new'
        end
    end

    def show
        
    end

    def edit

    end

    def update
        if @user.update(user_params)
            flash[:positive] = " User successfully updated"
            redirect_to user_path(@user)
        else
            render 'edit'
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end

    def set_user
        @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:negative] = "You must be logged in to perform that task"
            redirect_to login_path
        end
    end

end

app/helpers/users_helper.rb
module UsersHelper


end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular users teal icon"></i>
  Chat Room
</h4>

<div class="ui two column grid">
    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content" id="messages">
                <div class="ui small feed" id="message-container">
                    <%= render @messages %>
                </div>
            </div>
            <div class="extra content">
                <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f|  %>
                    <div class="field">
                        <div class="ui fluid icon input">
                            <%= f.text_field :body, autofocus: true  %>
                            <%= f.button '<i class="bordered inverted teal edit icon"></i>'.html_safe %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>

    <div class="four wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content">
                <div class="ui vertical menu">
                  <a class="active teal item">
                    Inbox
                    <div class="ui teal left pointing label">1</div>
                  </a>
                  <a class="teal item">
                    Spam
                    <div class="ui teal label">51</div>
                  </a>
                  <a class="teal item">
                    Updates
                    <div class="ui teal label">1</div>
                  </a>
                  <!-- <div class="teal item">
                    <div class="ui transparent icon input">
                      <input type="text" placeholder="Search mail...">
                      <i class="search icon"></i>
                    </div>
                  </div> -->
                </div>
            </div>
        </div>

    </div>

</div>

app/views/layouts/_messages.html.erb
<div class="ui container">
    <div class="row">
        <% flash.each do |name, msg| %>
            <div class="ui <%= "#{name}" %> message ">
                <i class="close icon"></i>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="ui inverted small menu">
    <div class="ui container">
        <%= link_to "Chatroom", root_path, class: "item" %>
        <a class="item">Messages</a>
        <div class="right menu">
            <div class="ui dropdown item">
                Account <i class="dropdown icon"></i>
                <div class="menu">
                    <% if logged_in? %>
                        <%= link_to "Log Out!", logout_path, class:"item", method: :delete %>
                        <%= link_to "Account setting", edit_user_path(current_user), class:"item" %>
                    <% else %>
                        <%= link_to "Login", login_path, class: "item" %>
                    <% end %>
                </div>
            </div>
            <% if !logged_in? %>
            <div class="item">
                <div class="ui inverted teal button">
                    <%= link_to "Sign Up!!", new_user_path %>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="ui container">
        <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
        <div class="summary">
            <%= message.user.username %> : <%= message.body %>
        </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="ui negative message">
        <div class="heading">
            <h3 class="title">
                <%= pluralize(obj.errors.count, "error") %>
                in form submission:
            </h3>
            <div class="body">
                <ul>
                    <% obj.errors.full_messages.each do |msg| %>
                        <li class="error_listing"><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_user_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for(@user, :html => {class:"form-horizontal ui form", role: "form"}) do |f| %>
    <div class="field">
        <%= f.label :username %>
        <%= f.text_field :username, class:"form-control", placeholder:"Enter Username", autofocus: true %>
    </div>
    <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password, class:"form-control", placeholder:"Enter password"%>
    </div>
    <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Enter password again"%>
    </div>
    <%= f.submit(@user.new_record? ? "Open Account!" : "Update Account", class:"ui button") %>
<% end %>

app/views/users/edit.html.erb
<h2 align="center" class="ui header">
    <i class="circular big grey inverted setting icon"></i>
</h2>
<h2 align="center" class="sub header">
    <%= @user.username %>
</h2>

<%= render 'user_form' %>

app/views/users/index.html.erb
<h4 class="ui center aligned medium icon header">
    Listing all users
</h4>

<div align="center" class="ui pagination menu grid">
    <%= will_paginate @users, renderer: WillPaginateSemanticUi::ActionView::Renderer %>
</div>

<div class="ui two column grid">
    <% @users.each do |user| %>
        <div class="column">
            <div class="ui cards">
                <div class="ui card">
                    <div class="content">
                        <%= link_to user.username, user_path(user), class: "header" %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<h2 align="center" class="ui header">
    <i class="circular big grey inverted user plus icon"></i>
</h2>
<h2 align="center" class="ui header 2">New User Signup</h2>
<%= render 'user_form' %>

app/views/users/show.html.erb
<h1 align="center" class="ui header">Welcome to <%= @user.username %>'s wall </h1>
<h4 align="center" class="ui subheader">More to come </h2>